#!/usr/bin/env perl
# A perl script to convert the CSV export of the 
# 2006 Norwegian Red List into a topic map
#
# See the artsdatabanken.no web site:
# http://www.artsdatabanken.no/Article.aspx?m=116&amid=2537
#
# Copyright 2010 by Jan Schreiber, <jan.schreiber [at] gmail.com>
# This library is free software; you can redistribute it
# and/or modify it under the same terms as Perl itself.
use strict;
use warnings;
use Text::CSV::Unicode;
use Data::Dumper;

my $file = $ARGV[0];

if (not $file) {
    print "USAGE: redlist2ctm.pl filename\n";
    exit;
}

# The order of species that we're going to convert into a topic map
# This is used to create human readable PSIs (Published Subject Identifiers)
# You might have to adjust this:
my $order = 'coleoptera';

my $csv = Text::CSV::Unicode->new();

open (CSV, "<", $file) or die $!;

my $skip = <CSV>;

print<<EOS;
%encoding "utf-8"
%version 1.0

#(
Information extracted from the CVS export of the Norwegian
artsdatabanken.no project:
http://www.artsdatabanken.no/Article.aspx?m=116&amid=2537
Topic map generated by redlist2ctm.pl
Version: 1.0
)#

%prefix tmcl http://psi.topicmaps.org/tmcl/
%prefix lang <http://psi.oasis-open.org/geolang/iso639/#>
%prefix redlist <http://psi.entomologi.org/redlist/>
%prefix redlist-category <http://psi.entomologi.org/redlist/category#>
%prefix ent <http://psi.entomologi.org/>

shortname isa tmcl:name-type;
    <http://psi.entomologi.org/name-type/shortname> .

full_species_name isa tmcl:name-type;
    <http://psi.entomologi.org/name-type/full_species_name> .

ent:artsdatabank_id isa tmcl:occurrence-type;
    - "Artsdatabank ID" .

redlist:criterion isa tmcl:topic-type;
    - "Criterion";
    - "Kriterium" @ lang:nno .

redlist:category isa tmcl:topic-type;
    - "Red List category";
    - "Rødlistekategori" @ lang:nno .

redlist-category:EX isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "EX";
    - "Extinct";
    - "Utdødd" @ lang:nno .
    
redlist-category:RE isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "RE";
    - "Regional extinct";
    - "Redionalt utdødd" @ lang:nno .

redlist-category:CR isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "CR";
    - "Critically Endangered";
    - "Kritisk truet" @ lang:nno .

redlist-category:EN isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "EN";
    - "Endangered";
    - "Sterkt truet" @ lang:nno .

redlist-category:VU isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "VU";
    - "Vulnerable";
    - "Sårbar" @ lang:nno .

redlist-category:NT isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "NT";
    - "Near Threatened";
    - "Nær truet" @ lang:nno .

redlist-category:NE isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "NE";
    - "Not Evaluated";
    - "Ikke vurdert" @ lang:nno .

redlist-category:DD isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "DD";
    - "Data Deficient";
    - "Datamangel" @ lang:nno .

redlist-category:LC isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "LC";
    - "Least Concern";
    - "Livskraftig" @ lang:nno .

redlist-category:NA isa tmcl:topic-type;
    ako redlist:category;
    - shortname: "NA";
    - "Not Applicable";
    - "Ikke egnet" @ lang:nno .

redlist:redlist2006 isa ent:redlist;
    - "2006 Norwegian Red List";
    - "Norsk Rødliste 2006" @ lang:nno .

redlist:is-redlisted-as isa tmcl:association-type;
    - "Is redlisted as";
    - "Er rødlisted som" @ lang:nno .

redlist:is-possibly-redlisted-as isa tmcl:association-type;
    - "Is redlisted as (uncertain)";
    - "Er rødlisted som (usikkert)" @ lang:nno .

EOS

while (<CSV>) {
    if ($csv->parse($_)) {
        my @columns = $csv->fields();
        my $art_name = $columns[2];
        my $art_id = lc($art_name);

        $art_id =~ s/[\s\.\-]/_/g;
        print "$art_id isa ent:species;\n".
            "    http://psi.entomologi.org/species/$order/$art_id;\n".
            "    <".$columns[7].">;\n";
        print "    ent:artsdatabank_id : ".$columns[0].";\n";
        if ($columns[3] ne '') {
            print "    - \"".$columns[3]."\" @ lang:nno;\n";
        }
        print "    - full_species_name: \"".$columns[2]."\" .\n";

        my $uncertain = 0;
        if (length $columns[5] > 2) {
            $columns[5] = substr $columns[5], 0, 2;
            $uncertain = 1;
        }
        my $atype;
        if ($uncertain eq 1) {
            $atype = 'is-possibly-redlisted-as';
        } else {
            $atype = 'is-redlisted-as';
        }
        if ($columns[6] ne "") {
            print "redlist:$atype(ent:species : $art_id,\n".
                "    redlist:category : redlist-category:".uc($columns[5]).",\n".
                "    redlist:criterion : ".$art_id."_crit) @ redlist:redlist2006\n";
            print $art_id."_crit isa redlist:criterion;\n".
                "     - \"".$columns[6]."\" .\n\n";
        } else {
            print "redlist:$atype(ent:species : $art_id,\n".
                "    redlist:category : redlist-category:".uc($columns[5]).") @ redlist:redlist2006\n\n";
        }
        #print "@columns\n";
    } else {
        my $err = $csv->error_input;
        print "# Failed to parse line: $err";
        print "#".Dumper($err);
    }
}
close CSV;
